@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.ofekn.crafting_on_a_stick.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;