# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.1-1.0
group=com.ofekn.crafting_on_a_stick
java_version=25
run_minecraft_version=26.2

# Common
minecraft_version=26.2
mod_name=Crafting on a Stick
mod_author=OfekN
mod_id=crafting_on_a_stick
license=GNU GENERAL PUBLIC LICENSE
credits=
description=Multiple workbenches on a stick
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
# compile against first stable release (such as 26.1)
neo_form_version=26.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
# run against last stable release (such as 26.1.2)
fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
# run against last stable release (such as 26.1.2)
neoforge_version=26.2.0.6-beta
neoforge_loader_version_range=[4,)

# Integrations
jei_version=30.0.0.3
jei_mc_version=26.2
curios_version=15.0.0-beta.1+26.1

# Runtime toggles
run_with_jei=true
run_with_curios=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
