@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.ofekn.crafting_on_a_stick;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;